### ISSUE TITLE
Prototype possible validation approaches

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/formio-builder#19]
- generically based on `component.validate` -> requires order/mapping with component type
- specify explicitly at the preview component level (e.g. map `component.type -> (component) => ZodSchema`)

**Comment by CharString** [comment]
"Parse don't validate" :heart_eyes: zod makes a good first impression.

**Comment by sergei-maertens** [comment]
I knew you'd like this ;)

**Comment by sergei-maertens** [comment]
Validation of the edit form is properly sorted out, doing this for the preview component is postponed/skipped:

* the new design doesn't have the preview component anymore (nor the edit modal)
* it's really the business of the renderer, so probably better to direct resources that way
