### ISSUE TITLE
Story doesn't work in Firefox

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/formio-builder#36]
See: https://github.com/open-formulieren/formio-builder/pull/34#discussion_r1317308962

In the story with path /story/builder-components-textfield--preview-initial-values, the interaction tests fail because clicking on the checkbox 'multiple values' doesn't seem to actually check the checkbox.

**Comment by sergei-maertens** [comment]
Fixed via fdb882974de791955ff4f3c6aa6b9d80575a8bab
