### ISSUE TITLE
Unable to add, edit date components

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/formio-builder#40]
### Product versie / Product version

latest / 2.4.0

### Omschrijf het probleem / Describe the bug

Adding a Date component brings up a modal, but cannot be saved. 
Also existing date components cannot be changed/updated. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/40a94b74-f2c6-4fb8-b8b1-6f703f50b92e)

**Comment by sergei-maertens** [comment]
I moved it - and can confirm the problem. I'll see how I can automate some tests to catch these sort of problems!
