### ISSUE TITLE
Preview does not update when changing field type in Storybook

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/formio-builder#49]
In the component edit form, changing the suffix field changes nothing on preview:

![image](https://github.com/open-formulieren/formio-builder/assets/65306057/83ba2c82-d6d0-47af-af17-a3072f171513)

EDIT: This seems to be an issue with storybook not updating the preview comment when we change the type from `textfield` to `number`

**Comment by sergei-maertens** [comment]
Type is not a formik field that is managed, and the preview only reacts to changes in the formik state.

Changing the type of a component after opening the edit modal is not supported as of now - formio also does not allow it.

The new design gets rid of the modal, let's see if we bring it in scope then
